site_name: BMO

theme:
  name: "readthedocs"

plugins:
  - search
  - autorefs
  - mkdocstrings:
      handlers:
        python:
          setup_command:
            - import sys
            - sys.path.append('../')
            - python -c "import bmo"
          selection:
            new_path_syntax: true


